# Generated by Django 5.2.5 on 2025-10-07 16:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Región')),
                ('codigo', models.CharField(max_length=5, unique=True, verbose_name='Código Región')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'db_table': 'region',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100, verbose_name='Razón Social')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre_ficticio', models.CharField(max_length=100, verbose_name='Nombre Ficticio Empresa')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('tipo_proveedor', models.CharField(choices=[('MP', 'Materia Prima'), ('PT', 'Productos Terminados'), ('EM', 'Embalaje'), ('EQ', 'Equipamiento'), ('SR', 'Servicios')], max_length=2, verbose_name='Tipo de Proveedor')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('S', 'Suspendido')], default='A', max_length=1, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('productos_que_abastece', models.TextField(max_length=500, verbose_name='Productos que Abastece')),
                ('tiempo_entrega_promedio', models.IntegerField(verbose_name='Tiempo de Entrega (días)')),
                ('certificaciones', models.TextField(blank=True, max_length=300, verbose_name='Certificaciones')),
                ('evaluacion_calidad', models.IntegerField(choices=[(1, '1 Estrella'), (2, '2 Estrellas'), (3, '3 Estrellas'), (4, '4 Estrellas'), (5, '5 Estrellas')], default=3, verbose_name='Evaluación de Calidad')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='proveedores.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['razon_social'],
            },
        ),
    ]
